//
// VapiStdErrorsInvalidArgumentError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VapiStdErrorsInvalidArgumentError: Codable {

    public var type: String?
    public var value: VapiStdErrorsInvalidArgument?

    public init(type: String?, value: VapiStdErrorsInvalidArgument?) {
        self.type = type
        self.value = value
    }


}

