//
// VapiStdErrorsInvalidElementTypeError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VapiStdErrorsInvalidElementTypeError: Codable {

    public var type: String?
    public var value: VapiStdErrorsInvalidElementType?

    public init(type: String?, value: VapiStdErrorsInvalidElementType?) {
        self.type = type
        self.value = value
    }


}

