//
// VapiStdErrorsResourceInUseError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VapiStdErrorsResourceInUseError: Codable {

    public var type: String?
    public var value: VapiStdErrorsResourceInUse?

    public init(type: String?, value: VapiStdErrorsResourceInUse?) {
        self.type = type
        self.value = value
    }


}

