//
// VapiStdErrorsAlreadyInDesiredStateError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VapiStdErrorsAlreadyInDesiredStateError: Codable {

    public var type: String?
    public var value: VapiStdErrorsAlreadyInDesiredState?

    public init(type: String?, value: VapiStdErrorsAlreadyInDesiredState?) {
        self.type = type
        self.value = value
    }


}

