//
// VcenterVMInstantCloneSpecNicsToUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVMInstantCloneSpecNicsToUpdate: Codable {

    public var key: String?
    public var value: VcenterVmHardwareEthernetUpdateSpec?

    public init(key: String?, value: VcenterVmHardwareEthernetUpdateSpec?) {
        self.key = key
        self.value = value
    }


}

