//
// VcenterVmHardwareParallelResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmHardwareParallelResp: Codable {

    public var value: VcenterVmHardwareParallelInfo

    public init(value: VcenterVmHardwareParallelInfo) {
        self.value = value
    }


}

