//
// VcenterVchaClusterActiveResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVchaClusterActiveResp: Codable {

    public var value: VcenterVchaClusterActiveInfo

    public init(value: VcenterVchaClusterActiveInfo) {
        self.value = value
    }


}

