//
// VcenterCryptoManagerKmsProvidersImportSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterCryptoManagerKmsProvidersImportSpec: Codable {

    /** Configuration to import. Currently this is required. Other import methods may be supported in the future. */
    public var config: Data?
    /** Password to decrypt the configuration to import. If unset or empty, configuration to import must be unencrypted. */
    public var password: String?
    /** Constraints to impose on the imported provider If unset, the imported provider constraints will match the exported provider constraints. */
    public var constraints: VcenterCryptoManagerKmsProvidersConstraintsSpec?
    /** Whether to perform a trial import without actuallly creating a provider. If unset, a new provider will be created. */
    public var dryRun: Bool?

    public init(config: Data?, password: String?, constraints: VcenterCryptoManagerKmsProvidersConstraintsSpec?, dryRun: Bool?) {
        self.config = config
        self.password = password
        self.constraints = constraints
        self.dryRun = dryRun
    }

    public enum CodingKeys: String, CodingKey { 
        case config
        case password
        case constraints
        case dryRun = "dry_run"
    }


}

