//
// VcenterContentRegistriesHarborProjectsCreateSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterContentRegistriesHarborProjectsCreateSpec: Codable {

    /** Name of the Harbor project. Should be between 1-63 characters long alphanumeric string and may contain the following characters: a-z,0-9, and &#39;-&#39;. Must be starting with characters or numbers, with the &#39;-&#39; character allowed anywhere except the first or last character. */
    public var name: String
    /** Access type of a Harbor project. */
    public var scope: VcenterContentRegistriesHarborProjectsScope

    public init(name: String, scope: VcenterContentRegistriesHarborProjectsScope) {
        self.name = name
        self.scope = scope
    }


}

