//
// VcenterComputePoliciesTagUsageFilterSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterComputePoliciesTagUsageFilterSpec: Codable {

    /** Identifiers that compute policies must have to match the filter. If unset or empty, then tags used by any policy match this filter. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: vcenter.compute.Policy. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: vcenter.compute.Policy. */
    public var policies: [String]?
    /** Identifiers that tags must have to match the filter. If unset or empty, then tags with any tag identifier match this filter. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: cis.tagging.Tag. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: cis.tagging.Tag. */
    public var tags: [String]?
    /** Identifiers that tag types must have to match the filter. If unset or empty, then tags of any type match this filter. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: vapi.resource. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: vapi.resource. */
    public var tagTypes: [String]?

    public init(policies: [String]?, tags: [String]?, tagTypes: [String]?) {
        self.policies = policies
        self.tags = tags
        self.tagTypes = tagTypes
    }

    public enum CodingKeys: String, CodingKey { 
        case policies
        case tags
        case tagTypes = "tag_types"
    }


}

