//
// VcenterSystemConfigDeploymentTypeReconfigure.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterSystemConfigDeploymentTypeReconfigure: Codable {

    /** ReconfigureSpec to set the appliance type. */
    public var spec: VcenterSystemConfigDeploymentTypeReconfigureSpec

    public init(spec: VcenterSystemConfigDeploymentTypeReconfigureSpec) {
        self.spec = spec
    }


}

