//
// VcenterTrustedInfrastructureTrustAuthorityClustersSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterTrustedInfrastructureTrustAuthorityClustersSummary: Codable {

    /** Identifies the cluster. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: ClusterComputeResource. When operations return a value of this structure as a result, the field will be an identifier for the resource type: ClusterComputeResource. */
    public var cluster: String
    /** The state of the TrustAuthorityClusters. */
    public var state: VcenterTrustedInfrastructureTrustAuthorityClustersState

    public init(cluster: String, state: VcenterTrustedInfrastructureTrustAuthorityClustersState) {
        self.cluster = cluster
        self.state = state
    }


}

