//
// VcenterGuestCustomizationSpecsSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterGuestCustomizationSpecsSummary: Codable {

    /** Name of the guest customization specification. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: vcenter.guest.CustomizationSpec. When operations return a value of this structure as a result, the field will be an identifier for the resource type: vcenter.guest.CustomizationSpec. */
    public var name: String
    /** Description of the guest customization specification. */
    public var _description: String
    /** Guest operating system type for which that this guest customization specification applies. */
    public var oSType: VcenterGuestCustomizationSpecsOsType
    /** Date and tme when this guest customization specification was last modified. */
    public var lastModified: Date

    public init(name: String, _description: String, oSType: VcenterGuestCustomizationSpecsOsType, lastModified: Date) {
        self.name = name
        self._description = _description
        self.oSType = oSType
        self.lastModified = lastModified
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _description = "description"
        case oSType = "OS_type"
        case lastModified = "last_modified"
    }


}

