//
// VcenterNamespaceManagementSupervisorsTopologyInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementSupervisorsTopologyInfo: Codable {

    /** Identifier of this vSphere Zone. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: vcenter.consumption_domains.Zone. When operations return a value of this structure as a result, the field will be an identifier for the resource type: vcenter.consumption_domains.Zone. */
    public var zone: String
    /** A list of vSphere Cluster identifiers that are associated with the vSphere Zone. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: ClusterComputeResource. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: ClusterComputeResource. */
    public var clusters: [String]

    public init(zone: String, clusters: [String]) {
        self.zone = zone
        self.clusters = clusters
    }


}

