//
// VcenterVmHardwareAdapterScsiSharing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Scsi.Sharing enumerated type defines the valid bus sharing modes for a virtual SCSI adapter. */
public enum VcenterVmHardwareAdapterScsiSharing: String, Codable {
    case _none = "NONE"
    case virtual = "VIRTUAL"
    case physical = "PHYSICAL"

}
