//
// VcenterDeploymentUpgradeVcsaEmbeddedSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterDeploymentUpgradeVcsaEmbeddedSpec: Codable {

    /** Customer experience improvement program should be enabled or disabled for this embedded vCenter Server upgrade. */
    public var ceipEnabled: Bool

    public init(ceipEnabled: Bool) {
        self.ceipEnabled = ceipEnabled
    }

    public enum CodingKeys: String, CodingKey { 
        case ceipEnabled = "ceip_enabled"
    }


}

