//
// VcenterVmHardwareAdapterScsiInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmHardwareAdapterScsiInfo: Codable {

    /** Device label. */
    public var label: String
    /** Adapter type. */
    public var type: VcenterVmHardwareAdapterScsiType
    /** Address of the SCSI adapter on the SCSI bus. */
    public var scsi: VcenterVmHardwareScsiAddressInfo
    /** Address of the SCSI adapter on the PCI bus. If the PCI address is invalid, the server will change it when the VM is started or as the device is hot added. May be unset if the virtual machine has never been powered on since the adapter was created. */
    public var pciSlotNumber: Int64?
    /** Bus sharing mode. */
    public var sharing: VcenterVmHardwareAdapterScsiSharing

    public init(label: String, type: VcenterVmHardwareAdapterScsiType, scsi: VcenterVmHardwareScsiAddressInfo, pciSlotNumber: Int64?, sharing: VcenterVmHardwareAdapterScsiSharing) {
        self.label = label
        self.type = type
        self.scsi = scsi
        self.pciSlotNumber = pciSlotNumber
        self.sharing = sharing
    }

    public enum CodingKeys: String, CodingKey { 
        case label
        case type
        case scsi
        case pciSlotNumber = "pci_slot_number"
        case sharing
    }


}

