//
// VcenterDeploymentResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterDeploymentResp: Codable {

    public var value: VcenterDeploymentInfo

    public init(value: VcenterDeploymentInfo) {
        self.value = value
    }


}

