//
// VcenterNamespaceManagementSupervisorsWorkloadsStorageConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementSupervisorsWorkloadsStorageConfig: Codable {

    /** WorkloadsStorageConfig.cloud-native-file-volume specifies the Cloud Native Storage file volume support on the Supervisor. This feature provides ReadWriteMany container volumes support. If unset, file volume support will not be enabled on the Supervisor. */
    public var cloudNativeFileVolume: VcenterNamespaceManagementSupervisorsCNSFileConfig?
    /** WorkloadsStorageConfig.ephemeral-storage-policy identifies the storage policy associated with ephemeral disks of all the Kubernetes PodVMs in the cluster. If unset during cluster enablement, the ephemeral storage policy will be defaulted to the configured ControlPlane.storage-policy. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: SpsStorageProfile. When operations return a value of this structure as a result, the field will be an identifier for the resource type: SpsStorageProfile. */
    public var ephemeralStoragePolicy: String?
    /** The WorkloadsStorageConfig.image-storage-policy structure contains the specification required to configure storage used for PodVM container images. If unset, the image storage policy will be set to the specified WorkloadsStorageConfig.ephemeral-storage-policy if provided. This field will inherit any defaults for ephemeral storage policy set by the system. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: SpsStorageProfile. When operations return a value of this structure as a result, the field will be an identifier for the resource type: SpsStorageProfile. */
    public var imageStoragePolicy: String?

    public init(cloudNativeFileVolume: VcenterNamespaceManagementSupervisorsCNSFileConfig?, ephemeralStoragePolicy: String?, imageStoragePolicy: String?) {
        self.cloudNativeFileVolume = cloudNativeFileVolume
        self.ephemeralStoragePolicy = ephemeralStoragePolicy
        self.imageStoragePolicy = imageStoragePolicy
    }

    public enum CodingKeys: String, CodingKey { 
        case cloudNativeFileVolume = "cloud_native_file_volume"
        case ephemeralStoragePolicy = "ephemeral_storage_policy"
        case imageStoragePolicy = "image_storage_policy"
    }


}

