//
// VcenterVmHardwareUpgradeStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Hardware.UpgradeStatus enumerated type defines the valid virtual hardware upgrade statuses for a virtual machine. */
public enum VcenterVmHardwareUpgradeStatus: String, Codable {
    case _none = "NONE"
    case pending = "PENDING"
    case success = "SUCCESS"
    case failed = "FAILED"

}
