//
// VcenterNamespaceManagementSupervisorServicesCarvelCreateSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementSupervisorServicesCarvelCreateSpec: Codable {

    /** Supervisor service version specification that provides the service definitions for one Supervisor Service version. */
    public var versionSpec: VcenterNamespaceManagementSupervisorServicesVersionsCarvelCreateSpec

    public init(versionSpec: VcenterNamespaceManagementSupervisorServicesVersionsCarvelCreateSpec) {
        self.versionSpec = versionSpec
    }

    public enum CodingKeys: String, CodingKey { 
        case versionSpec = "version_spec"
    }


}

