//
// VcenterLcmUpdatePendingListResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterLcmUpdatePendingListResult: Codable {

    /** Time when the software depo was last checked. */
    public var lastCheckTime: Date
    /** Number of pending updates Only set if there are available updates */
    public var updateCount: Int64?
    /** Number of pending upgrades Only set if there are available upgrades */
    public var upgradeCount: Int64?
    /** List of pending update details */
    public var updates: [VcenterLcmUpdatePendingSummary]
    /** Lists of issues encountered during pending updates retrieval. set if any issues encountered. */
    public var issues: VcenterLcmNotifications?

    public init(lastCheckTime: Date, updateCount: Int64?, upgradeCount: Int64?, updates: [VcenterLcmUpdatePendingSummary], issues: VcenterLcmNotifications?) {
        self.lastCheckTime = lastCheckTime
        self.updateCount = updateCount
        self.upgradeCount = upgradeCount
        self.updates = updates
        self.issues = issues
    }

    public enum CodingKeys: String, CodingKey { 
        case lastCheckTime = "last_check_time"
        case updateCount = "update_count"
        case upgradeCount = "upgrade_count"
        case updates
        case issues
    }


}

