//
// VcenterTrustedInfrastructureNetworkAddress.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterTrustedInfrastructureNetworkAddress: Codable {

    /** The IP address or DNS resolvable name of the service. */
    public var hostname: String
    /** The port of the service. If unset, port 443 will be used. */
    public var port: Int64?

    public init(hostname: String, port: Int64?) {
        self.hostname = hostname
        self.port = port
    }


}

