//
// VcenterVmGuestDhcpConfigInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmGuestDhcpConfigInfo: Codable {

    /** True if IPv4 DHCP is enabled, false otherwise. */
    public var ipv4Enabled: Bool
    /** True if IPv6 DHCP is enabled, false otherwise. */
    public var ipv6Enabled: Bool

    public init(ipv4Enabled: Bool, ipv6Enabled: Bool) {
        self.ipv4Enabled = ipv4Enabled
        self.ipv6Enabled = ipv6Enabled
    }

    public enum CodingKeys: String, CodingKey { 
        case ipv4Enabled = "ipv4_enabled"
        case ipv6Enabled = "ipv6_enabled"
    }


}

