//
// VcenterVmGuestFilesystemTransfersCreateSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmGuestFilesystemTransfersCreateSpec: Codable {

    /** The complete destination path in the guest to transfer the file to or from the client. It cannot be a path to a directory or a symbolic link. */
    public var path: String
    /** Details about the file to be transferred into the guest. Must be set if the file is being transferred to the guest. Must not be set if the file is being transferred from the guest. */
    public var attributes: VcenterVmGuestFilesystemTransfersFileCreationAttributes?

    public init(path: String, attributes: VcenterVmGuestFilesystemTransfersFileCreationAttributes?) {
        self.path = path
        self.attributes = attributes
    }


}

