//
// VcenterVmHardwareBootDeviceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Device.Type enumerated type defines the valid device types that may be used as bootable devices. */
public enum VcenterVmHardwareBootDeviceType: String, Codable {
    case cdrom = "CDROM"
    case disk = "DISK"
    case ethernet = "ETHERNET"
    case floppy = "FLOPPY"

}
