//
// VcenterVmGuestNetworkingResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmGuestNetworkingResp: Codable {

    public var value: VcenterVmGuestNetworkingInfo

    public init(value: VcenterVmGuestNetworkingInfo) {
        self.value = value
    }


}

