//
// VcenterVchaPlacementSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVchaPlacementSpec: Codable {

    /** The name of the VCHA node to be used for the virtual machine name. */
    public var name: String
    /** The identifier of the folder to deploy the VCHA node to. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: Folder:VCenter. When operations return a value of this structure as a result, the field will be an identifier for the resource type: Folder:VCenter. */
    public var folder: String
    /** The identifier of the host to deploy the VCHA node to. If unset, see vim.vm.RelocateSpec.host. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: HostSystem:VCenter. When operations return a value of this structure as a result, the field will be an identifier for the resource type: HostSystem:VCenter. */
    public var host: String?
    /** The identifier of the resource pool to deploy the VCHA node to. If unset, then the active node&#39;s resource pool will be used. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: ResourcePool:VCenter. When operations return a value of this structure as a result, the field will be an identifier for the resource type: ResourcePool:VCenter. */
    public var resourcePool: String?
    /** The type of the Network object used by the HA network.  If the PlacementSpec.ha-network field is set, then the PlacementSpec.ha-network-type field must be set.  If the PlacementSpec.ha-network field is unset, then the PlacementSpec.ha-network-type field is ignored. If unset and the PlacementSpec.ha-network field is unset, then the same network present on the Active node virtual machine is used to deploy the virtual machine with an assumption that the network is present on the destination.  If unset and the PlacementSpec.ha-network field is set, then an error is reported. */
    public var haNetworkType: VcenterVchaNetworkType?
    /** The identifier of the Network object used for the HA network.  If the PlacementSpec.ha-network field is set, then the {#link #haNetworkType} field must be set.  If the PlacementSpec.ha-network field is unset, then the PlacementSpec.ha-network-type field is ignored. If unset and the PlacementSpec.ha-network-type field is unset, then the same network present on the Active node virtual machine is used to deploy the virtual machine with an assumption that the network is present on the destination.  When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: Network:VCenter. When operations return a value of this structure as a result, the field will be an identifier for the resource type: Network:VCenter. */
    public var haNetwork: String?
    /** The type of the Network object used by the Management network.  If the PlacementSpec.management-network field is set, then the {#link #managementNetworkType} field must be set.  If the PlacementSpec.management-network field is unset, then the PlacementSpec.management-network-type field is ignored. If unset and the PlacementSpec.management-network field is unset, then the same network present on the Active node virtual machine is used to deploy the virtual machine with an assumption that the network is present on the destination.  If unset and the PlacementSpec.management-network field is set, then an error is reported. */
    public var managementNetworkType: VcenterVchaNetworkType?
    /** The identifier of the Network object used for the Management network. If the PlacementSpec.management-network field is set, then the PlacementSpec.management-network-type field must be set.  If the PlacementSpec.management-network field is unset, then the PlacementSpec.management-network-type field is ignored. If unset and the PlacementSpec.management-network-type field is unset, then the same network present on the Active node virtual machine is used to deploy the virtual machine with an assumption that the network is present on the destination.  When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: Network:VCenter. When operations return a value of this structure as a result, the field will be an identifier for the resource type: Network:VCenter. */
    public var managementNetwork: String?
    /** The storage specification to deploy the VCHA node to. If unset, see vim.vm.RelocateSpec.datastore. */
    public var storage: VcenterVchaDiskSpec?

    public init(name: String, folder: String, host: String?, resourcePool: String?, haNetworkType: VcenterVchaNetworkType?, haNetwork: String?, managementNetworkType: VcenterVchaNetworkType?, managementNetwork: String?, storage: VcenterVchaDiskSpec?) {
        self.name = name
        self.folder = folder
        self.host = host
        self.resourcePool = resourcePool
        self.haNetworkType = haNetworkType
        self.haNetwork = haNetwork
        self.managementNetworkType = managementNetworkType
        self.managementNetwork = managementNetwork
        self.storage = storage
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case folder
        case host
        case resourcePool = "resource_pool"
        case haNetworkType = "ha_network_type"
        case haNetwork = "ha_network"
        case managementNetworkType = "management_network_type"
        case managementNetwork = "management_network"
        case storage
    }


}

