//
// VcenterNamespaceManagementSupervisorsSummaryFilterSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementSupervisorsSummaryFilterSpec: Codable {

    /** Matches Supervisors with Summary.Info.config-status equal to the specified value. if unset this filter is not applied. */
    public var configStatus: VcenterNamespaceManagementSupervisorsSummaryConfigStatus?
    /** Matches Supervisors with the Summary.Info.kubernetes-status equal to the specified value. if unset this filter is not applied. */
    public var kubernetesStatus: VcenterNamespaceManagementSupervisorsSummaryKubernetesStatus?

    public init(configStatus: VcenterNamespaceManagementSupervisorsSummaryConfigStatus?, kubernetesStatus: VcenterNamespaceManagementSupervisorsSummaryKubernetesStatus?) {
        self.configStatus = configStatus
        self.kubernetesStatus = kubernetesStatus
    }

    public enum CodingKeys: String, CodingKey { 
        case configStatus = "config_status"
        case kubernetesStatus = "kubernetes_status"
    }


}

