//
// VcenterNamespaceManagementNetworksNsxEdgesCompatibilitySummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementNetworksNsxEdgesCompatibilitySummary: Codable {

    /** Identifier of the Edge. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: NSXEdgeCluster. When operations return a value of this structure as a result, the field will be an identifier for the resource type: NSXEdgeCluster. */
    public var edgeCluster: String
    /** User-friendly identifier of the Edge. */
    public var name: String
    /** Compatibility of this Edge with vSphere Namespaces. */
    public var compatible: Bool
    /** List of reasons for incompatibility. If empty, this Edge is compatible. */
    public var incompatibilityReasons: [VapiStdLocalizableMessage]

    public init(edgeCluster: String, name: String, compatible: Bool, incompatibilityReasons: [VapiStdLocalizableMessage]) {
        self.edgeCluster = edgeCluster
        self.name = name
        self.compatible = compatible
        self.incompatibilityReasons = incompatibilityReasons
    }

    public enum CodingKeys: String, CodingKey { 
        case edgeCluster = "edge_cluster"
        case name
        case compatible
        case incompatibilityReasons = "incompatibility_reasons"
    }


}

