//
// VcenterVmConsoleTicketsSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmConsoleTicketsSummary: Codable {

    /** Console ticket URI */
    public var ticket: String

    public init(ticket: String) {
        self.ticket = ticket
    }


}

