//
// VcenterContentRegistriesHarborProjectsResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterContentRegistriesHarborProjectsResp: Codable {

    public var value: VcenterContentRegistriesHarborProjectsInfo

    public init(value: VcenterContentRegistriesHarborProjectsInfo) {
        self.value = value
    }


}

