//
// VcenterNamespaceManagementVirtualMachineClassesConfigStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** ConfigStatus represents the config status of the VM class. */
public enum VcenterNamespaceManagementVirtualMachineClassesConfigStatus: String, Codable {
    case ready = "READY"
    case removing = "REMOVING"

}
