//
// VcenterVmHardwareDiskListResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmHardwareDiskListResp: Codable {

    public var value: [VcenterVmHardwareDiskSummary]

    public init(value: [VcenterVmHardwareDiskSummary]) {
        self.value = value
    }


}

