//
// VcenterVmHardwareSerialSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmHardwareSerialSummary: Codable {

    /** Identifier of the virtual serial port. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: vcenter.vm.hardware.SerialPort. When operations return a value of this structure as a result, the field will be an identifier for the resource type: vcenter.vm.hardware.SerialPort. */
    public var port: String

    public init(port: String) {
        self.port = port
    }


}

