//
// VcenterTrustedInfrastructureTrustAuthorityHostsAttestationFilterSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterTrustedInfrastructureTrustAuthorityHostsAttestationFilterSpec: Codable {

    /** A set of host IDs by which to filter the services. If unset, the services will not be filtered by the hosts on which they run. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: HostSystem. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: HostSystem. */
    public var hosts: [String]?
    /** A set of cluster IDs by which to filter the services. If unset, the services will not be filtered by the clusters on which they run. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: ClusterComputeResource. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: ClusterComputeResource. */
    public var clusters: [String]?
    /** The service&#39;s address. If unset, the services will not be filtered by address. */
    public var address: [VcenterTrustedInfrastructureNetworkAddress]?
    /** The group IDs determines which Attestation Service instances this Attestation Service can communicate with. If unset, the services will not be filtered by groupId. */
    public var groups: [String]?

    public init(hosts: [String]?, clusters: [String]?, address: [VcenterTrustedInfrastructureNetworkAddress]?, groups: [String]?) {
        self.hosts = hosts
        self.clusters = clusters
        self.address = address
        self.groups = groups
    }


}

