//
// VcenterDatastoreType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum VcenterDatastoreType: String, Codable {
    case vmfs = "VMFS"
    case nfs = "NFS"
    case nfs41 = "NFS41"
    case cifs = "CIFS"
    case vsan = "VSAN"
    case vffs = "VFFS"
    case vvol = "VVOL"

}
