//
// VcenterNamespaceManagementVirtualMachineClassesInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementVirtualMachineClassesInfo: Codable {

    /** Identifier for the VM class. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: vcenter.namespace_management.VirtualMachineClass. When operations return a value of this structure as a result, the field will be an identifier for the resource type: vcenter.namespace_management.VirtualMachineClass. */
    public var _id: String
    /** The number of CPUs configured for virtual machine of this class. */
    public var cpuCount: Int64
    /** The percentage of total available CPUs reserved for a virtual machine. We multiply this percentage by the minimum frequency amongst all the cluster nodes to get the CPU reservation that is specified to vSphere in MHz. If unset, no CPU reservation is requested for the virtual machine. */
    public var cpuReservation: Int64?
    /** The amount of memory in MB configured for virtual machine of this class. */
    public var memoryMB: Int64
    /** The percentage of available memory reserved for a virtual machine of this class. If unset, no memory reservation is requested for virtual machine. */
    public var memoryReservation: Int64?
    /** Description of the VM class. */
    public var _description: String
    /** Set of Namespaces associated with this VM class. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: vcenter.namespaces.Instance. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: vcenter.namespaces.Instance. */
    public var namespaces: [String]
    /** Set of virtual machines deployed for VM class. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: VirtualMachine. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: VirtualMachine. */
    public var vms: [String]
    /** Configstatus of VM class */
    public var configStatus: VcenterNamespaceManagementVirtualMachineClassesConfigStatus
    /** Current set of messages associated with the object. */
    public var messages: [VcenterNamespaceManagementVirtualMachineClassesMessage]
    /** Virtual devices corresponding to the VM class. This field is optional because it was added in a newer version than its parent node. */
    public var devices: VcenterNamespaceManagementVirtualMachineClassesVirtualDevices?
    /** Instance storage associated with the VM class. If unset, no instance storage is present. */
    public var instanceStorage: VcenterNamespaceManagementVirtualMachineClassesInstanceStorage?

    public init(_id: String, cpuCount: Int64, cpuReservation: Int64?, memoryMB: Int64, memoryReservation: Int64?, _description: String, namespaces: [String], vms: [String], configStatus: VcenterNamespaceManagementVirtualMachineClassesConfigStatus, messages: [VcenterNamespaceManagementVirtualMachineClassesMessage], devices: VcenterNamespaceManagementVirtualMachineClassesVirtualDevices?, instanceStorage: VcenterNamespaceManagementVirtualMachineClassesInstanceStorage?) {
        self._id = _id
        self.cpuCount = cpuCount
        self.cpuReservation = cpuReservation
        self.memoryMB = memoryMB
        self.memoryReservation = memoryReservation
        self._description = _description
        self.namespaces = namespaces
        self.vms = vms
        self.configStatus = configStatus
        self.messages = messages
        self.devices = devices
        self.instanceStorage = instanceStorage
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case cpuCount = "cpu_count"
        case cpuReservation = "cpu_reservation"
        case memoryMB = "memory_MB"
        case memoryReservation = "memory_reservation"
        case _description = "description"
        case namespaces
        case vms
        case configStatus = "config_status"
        case messages
        case devices
        case instanceStorage = "instance_storage"
    }


}

