//
// VcenterGuestCustomizationSpecsFormat.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The CustomizationSpecs.Format enumerated type specifies the formats the customization specification can be exported to. */
public enum VcenterGuestCustomizationSpecsFormat: String, Codable {
    case json = "JSON"
    case xml = "XML"

}
