//
// VcenterStoragePoliciesComplianceFilterSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterStoragePoliciesComplianceFilterSpec: Codable {

    /** Compliance Status that a virtual machine must have to match the filter. */
    public var status: [VcenterStoragePoliciesComplianceStatus]

    public init(status: [VcenterStoragePoliciesComplianceStatus]) {
        self.status = status
    }


}

