//
// VcenterHvcLinksSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterHvcLinksSummary: Codable {

    /** Unique identifier for the link. *Warning:* This attribute is available as Technology Preview. These are early access APIs provided to test, automate and provide feedback on the feature. Since this can change based on feedback, VMware does not guarantee backwards compatibility and recommends against using them in production environments. Some Technology Preview APIs might only be applicable to specific environments. */
    public var link: String
    /** The display name is set to the domain name which was set during create. *Warning:* This attribute is available as Technology Preview. These are early access APIs provided to test, automate and provide feedback on the feature. Since this can change based on feedback, VMware does not guarantee backwards compatibility and recommends against using them in production environments. Some Technology Preview APIs might only be applicable to specific environments. */
    public var displayName: String

    public init(link: String, displayName: String) {
        self.link = link
        self.displayName = displayName
    }

    public enum CodingKeys: String, CodingKey { 
        case link
        case displayName = "display_name"
    }


}

