//
// VcenterOvfParseIssue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterOvfParseIssue: Codable {

    /** The category of the parse issue. */
    public var category: VcenterOvfParseIssueCategory
    /** The name of the file in which the parse issue was found. */
    public var file: String
    /** The line number of the line in the file (see {@link #file}) where the parse issue was found (or -1 if not applicable). */
    public var lineNumber: Int64
    /** The position in the line (see {@link #lineNumber}) (or -1 if not applicable). */
    public var columnNumber: Int64
    /** A localizable message describing the parse issue. */
    public var message: VapiStdLocalizableMessage

    public init(category: VcenterOvfParseIssueCategory, file: String, lineNumber: Int64, columnNumber: Int64, message: VapiStdLocalizableMessage) {
        self.category = category
        self.file = file
        self.lineNumber = lineNumber
        self.columnNumber = columnNumber
        self.message = message
    }

    public enum CodingKeys: String, CodingKey { 
        case category
        case file
        case lineNumber = "line_number"
        case columnNumber = "column_number"
        case message
    }


}

