//
// VcenterVmGuestCustomizationInfoStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Customization.Info.Status enumerated type defines the status values that can be reported for the customization operation. */
public enum VcenterVmGuestCustomizationInfoStatus: String, Codable {
    case idle = "IDLE"
    case pending = "PENDING"
    case running = "RUNNING"
    case succeeded = "SUCCEEDED"
    case failed = "FAILED"

}
