//
// VcenterNamespaceManagementLoadBalancersServer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementLoadBalancersServer: Codable {

    /** Load balancer hostname or IPv4 address. */
    public var host: String
    /** Load balancer port. */
    public var port: Int64

    public init(host: String, port: Int64) {
        self.host = host
        self.port = port
    }


}

