//
// VcenterDeploymentMigrateActiveDirectoryCheckSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterDeploymentMigrateActiveDirectoryCheckSpec: Codable {

    /** IP addresses of the DNS servers of the Active Directory server. */
    public var dnsServers: [String]
    /** The domain name of the Active Directory server to which the migrated vCenter Server appliance should be joined. */
    public var domain: String
    /** Active Directory user that has permission to join the Active Directory after the vCenter Server is migrated to appliance. */
    public var username: String
    /** Active Directory user password that has permission to join the Active Directory after the vCenter Server is migrated to appliance. */
    public var password: String

    public init(dnsServers: [String], domain: String, username: String, password: String) {
        self.dnsServers = dnsServers
        self.domain = domain
        self.username = username
        self.password = password
    }

    public enum CodingKeys: String, CodingKey { 
        case dnsServers = "dns_servers"
        case domain
        case username
        case password
    }


}

