//
// VcenterVmTemplateLibraryItemsDeploySpecDiskStoragePolicyType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Policy type for the deployed virtual machine&#39;s disk. */
public enum VcenterVmTemplateLibraryItemsDeploySpecDiskStoragePolicyType: String, Codable {
    case specifiedPolicy = "USE_SPECIFIED_POLICY"
    case sourcePolicy = "USE_SOURCE_POLICY"

}
