//
// VcenterVmHardwareAdapterScsiUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmHardwareAdapterScsiUpdate: Codable {

    /** Specification for updating the virtual SCSI adapter. */
    public var spec: VcenterVmHardwareAdapterScsiUpdateSpec

    public init(spec: VcenterVmHardwareAdapterScsiUpdateSpec) {
        self.spec = spec
    }


}

