//
// VcenterHvcLinksSyncProvidersSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterHvcLinksSyncProvidersSummary: Codable {

    /** Sync provider id *Warning:* This attribute is available as Technology Preview. These are early access APIs provided to test, automate and provide feedback on the feature. Since this can change based on feedback, VMware does not guarantee backwards compatibility and recommends against using them in production environments. Some Technology Preview APIs might only be applicable to specific environments. */
    public var provider: String

    public init(provider: String) {
        self.provider = provider
    }


}

