//
// VcenterVmStoragePolicyDiskPolicySpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmStoragePolicyDiskPolicySpec: Codable {

    /** Policy type to be used while performing update operation on the virtual disks. */
    public var type: VcenterVmStoragePolicyDiskPolicySpecPolicyType
    /** Storage Policy identification. This field is optional and it is only relevant when the value of Policy.DiskPolicySpec.type is USE_SPECIFIED_POLICY. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: vcenter.StoragePolicy. When operations return a value of this structure as a result, the field will be an identifier for the resource type: vcenter.StoragePolicy. */
    public var policy: String?

    public init(type: VcenterVmStoragePolicyDiskPolicySpecPolicyType, policy: String?) {
        self.type = type
        self.policy = policy
    }


}

