//
// VcenterGuestCustomizationSpecsExport.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterGuestCustomizationSpecsExport: Codable {

    /** The format in which the customization specification has to be returned. */
    public var format: VcenterGuestCustomizationSpecsFormat

    public init(format: VcenterGuestCustomizationSpecsFormat) {
        self.format = format
    }


}

