//
// VcenterNamespacesNamespaceTemplatesResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespacesNamespaceTemplatesResp: Codable {

    public var value: VcenterNamespacesNamespaceTemplatesInfo

    public init(value: VcenterNamespacesNamespaceTemplatesInfo) {
        self.value = value
    }


}

