//
// VcenterStoragePoliciesComplianceVMListResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterStoragePoliciesComplianceVMListResp: Codable {

    public var value: [VcenterStoragePoliciesComplianceVMListRespValue]

    public init(value: [VcenterStoragePoliciesComplianceVMListRespValue]) {
        self.value = value
    }


}

