//
// VcenterHostCreateSpecThumbprintVerification.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Host.CreateSpec.ThumbprintVerification enumerated type defines the thumbprint verification schemes for a host&#39;s SSL certificate. */
public enum VcenterHostCreateSpecThumbprintVerification: String, Codable {
    case _none = "NONE"
    case thumbprint = "THUMBPRINT"

}
