//
// VcenterVMCloneSpecDisksToUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVMCloneSpecDisksToUpdate: Codable {

    public var key: String?
    public var value: VcenterVMDiskCloneSpec?

    public init(key: String?, value: VcenterVMDiskCloneSpec?) {
        self.key = key
        self.value = value
    }


}

