//
// VcenterVmTemplateLibraryItemsResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmTemplateLibraryItemsResp: Codable {

    public var value: VcenterVmTemplateLibraryItemsInfo

    public init(value: VcenterVmTemplateLibraryItemsInfo) {
        self.value = value
    }


}

