//
// VcenterHvcLinksListResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterHvcLinksListResp: Codable {

    public var value: [VcenterHvcLinksSummary]

    public init(value: [VcenterHvcLinksSummary]) {
        self.value = value
    }


}

