//
// VcenterServicesServiceListDetailsResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterServicesServiceListDetailsResp: Codable {

    public var value: [VcenterServicesServiceListDetailsRespValue]

    public init(value: [VcenterServicesServiceListDetailsRespValue]) {
        self.value = value
    }


}

