//
// VcenterNamespaceManagementSupervisorServicesValidationStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The SupervisorServices.ValidationStatus enumerated type defines the type of status for validating content of a Supervisor Service version. */
public enum VcenterNamespaceManagementSupervisorServicesValidationStatus: String, Codable {
    case valid = "VALID"
    case validWithWarnings = "VALID_WITH_WARNINGS"
    case invalid = "INVALID"

}
