//
// VcenterTrustedInfrastructureHostsHardwareTpmEndorsementKeysType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum VcenterTrustedInfrastructureHostsHardwareTpmEndorsementKeysType: String, Codable {
    case rsa2048 = "RSA_2048"
    case eccNistP256 = "ECC_NIST_P_256"

}
