//
// VcenterVmGuestEnvironmentList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmGuestEnvironmentList: Codable {

    /** The guest authentication data. See Credentials. */
    public var credentials: VcenterVmGuestCredentials
    /** The names of the variables to be read. If the set is empty, then all the environment variables are returned. */
    public var names: [String]

    public init(credentials: VcenterVmGuestCredentials, names: [String]) {
        self.credentials = credentials
        self.names = names
    }


}

