//
// VcenterOvfLibraryItemOvfSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterOvfLibraryItemOvfSummary: Codable {

    /** Default name for the virtual machine or virtual appliance. */
    public var name: String?
    /** Default annotation for the virtual machine or virtual appliance. */
    public var annotation: String?
    /** End User License Agreements specified in the OVF descriptor. All end user license agreements must be accepted in order for the {@name LibraryItem#deploy} {@term operation} to succeed. See {@link ResourcePoolDeploymentSpec#acceptAllEula}. */
    public var eULAs: [String]
    /** Section identifiers for sections of type ovf:NetworkSection in the OVF descriptor. These identifiers can be used as keys in {@link ResourcePoolDeploymentSpec#networkMappings}. */
    public var networks: [String]?
    /** Section identifiers for sections of type vmw:StorageGroupSection in the OVF descriptor. These identifiers can be used as keys in {@link ResourcePoolDeploymentSpec#storageMappings}. */
    public var storageGroups: [String]?
    /** Additional OVF parameters which can be specified for the deployment target. These OVF parameters can be inspected, optionally modified, and used as values in {@link ResourcePoolDeploymentSpec#additionalParameters} for the {@name LibraryItem#deploy} {@term operation}. */
    public var additionalParams: [JSONValue]?

    public init(name: String?, annotation: String?, eULAs: [String], networks: [String]?, storageGroups: [String]?, additionalParams: [JSONValue]?) {
        self.name = name
        self.annotation = annotation
        self.eULAs = eULAs
        self.networks = networks
        self.storageGroups = storageGroups
        self.additionalParams = additionalParams
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case annotation
        case eULAs = "EULAs"
        case networks
        case storageGroups = "storage_groups"
        case additionalParams = "additional_params"
    }


}

