//
// VcenterVmStoragePolicyVmHomePolicySpecPolicyType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Policy.VmHomePolicySpec.PolicyType enumerated type defines the choices for how to specify the policy to be associated with the virtual machine home&#39;s directory. */
public enum VcenterVmStoragePolicyVmHomePolicySpecPolicyType: String, Codable {
    case specifiedPolicy = "USE_SPECIFIED_POLICY"
    case defaultPolicy = "USE_DEFAULT_POLICY"

}
