//
// VcenterNamespaceManagementSupervisorsEnableOnZonesSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementSupervisorsEnableOnZonesSpec: Codable {

    /** Supervisors.EnableOnZonesSpec.zones describe consumption fault domain zones available to the Supervisor and its workloads. Only one or three zones are supported. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: vcenter.consumption_domains.Zone. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: vcenter.consumption_domains.Zone. */
    public var zones: [String]
    /** A Supervisors.EnableSpec.name is a user-friendly identifier for this Supervisor. */
    public var name: String
    /** Supervisors.EnableSpec.control-plane specifies configuration for the Supervisor control plane. */
    public var controlPlane: VcenterNamespaceManagementSupervisorsControlPlane
    /** Supervisors.EnableSpec.workloads specifies configuration for compute, network, and storage for workloads. */
    public var workloads: VcenterNamespaceManagementSupervisorsWorkloads

    public init(zones: [String], name: String, controlPlane: VcenterNamespaceManagementSupervisorsControlPlane, workloads: VcenterNamespaceManagementSupervisorsWorkloads) {
        self.zones = zones
        self.name = name
        self.controlPlane = controlPlane
        self.workloads = workloads
    }

    public enum CodingKeys: String, CodingKey { 
        case zones
        case name
        case controlPlane = "control_plane"
        case workloads
    }


}

