//
// VcenterCertificateManagementVcenterTlsReplaceVmcaSigned.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterCertificateManagementVcenterTlsReplaceVmcaSigned: Codable {

    /** The information needed to generate VMCA signed Machine SSL */
    public var spec: VcenterCertificateManagementVcenterTlsReplaceSpec

    public init(spec: VcenterCertificateManagementVcenterTlsReplaceSpec) {
        self.spec = spec
    }


}

