//
// VcenterNamespaceManagementSupervisorServicesUpdateSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementSupervisorServicesUpdateSpec: Codable {

    /** A human readable name of the Supervisor Service. If unset, the display name of the service will not be modified. */
    public var displayName: String?
    /** A human readable description of the Supervisor Service. If unset, the description of the service will not be modified. */
    public var _description: String?

    public init(displayName: String?, _description: String?) {
        self.displayName = displayName
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case displayName = "display_name"
        case _description = "description"
    }


}

