//
// VcenterNamespaceManagementSupervisorsSummaryKubernetesStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Summary.KubernetesStatus enumerated type describes the Supervisor&#39;s ability to deploy pods. */
public enum VcenterNamespaceManagementSupervisorsSummaryKubernetesStatus: String, Codable {
    case ready = "READY"
    case warning = "WARNING"
    case error = "ERROR"

}
