//
// VcenterNamespaceManagementClustersImageStorageSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementClustersImageStorageSpec: Codable {

    /** Identifier of the storage policy. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: SpsStorageProfile. When operations return a value of this structure as a result, the field will be an identifier for the resource type: SpsStorageProfile. */
    public var storagePolicy: String

    public init(storagePolicy: String) {
        self.storagePolicy = storagePolicy
    }

    public enum CodingKeys: String, CodingKey { 
        case storagePolicy = "storage_policy"
    }


}

