//
// VcenterCertificateManagementVcenterTrustedRootChainsCreateSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterCertificateManagementVcenterTrustedRootChainsCreateSpec: Codable {

    /** Certificate chain in base64 encoding */
    public var certChain: VcenterCertificateManagementX509CertChain
    /** Unique identifier for this trusted root. Client can specify at creation as long as it is unique, otherwise one will be generated. An example of a client providing the identifier would be if this trusted root is associated with a VC trust. In this case the identifier would be the domain id. A unique id will be generated if not given. */
    public var chain: String?

    public init(certChain: VcenterCertificateManagementX509CertChain, chain: String?) {
        self.certChain = certChain
        self.chain = chain
    }

    public enum CodingKeys: String, CodingKey { 
        case certChain = "cert_chain"
        case chain
    }


}

