//
// VcenterVmHardwareFloppyBackingType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Floppy.BackingType enumerated type defines the valid backing types for a virtual floppy drive. */
public enum VcenterVmHardwareFloppyBackingType: String, Codable {
    case imageFile = "IMAGE_FILE"
    case hostDevice = "HOST_DEVICE"
    case clientDevice = "CLIENT_DEVICE"

}
