//
// VcenterCryptoManagerKmsProvidersHealth.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum VcenterCryptoManagerKmsProvidersHealth: String, Codable {
    case _none = "NONE"
    case ok = "OK"
    case warning = "WARNING"
    case error = "ERROR"

}
