//
// VcenterNamespaceManagementSupervisorServicesClusterSupervisorServicesMessageMessageSeverity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The ClusterSupervisorServices.Message.MessageSeverity enumerated type represents the severity of the message. */
public enum VcenterNamespaceManagementSupervisorServicesClusterSupervisorServicesMessageMessageSeverity: String, Codable {
    case info = "INFO"
    case warning = "WARNING"
    case error = "ERROR"

}
