//
// VcenterVmTemplateLibraryItemsGuestCustomizationSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmTemplateLibraryItemsGuestCustomizationSpec: Codable {

    /** Name of the customization specification. */
    public var name: String?

    public init(name: String?) {
        self.name = name
    }


}

