//
// VcenterSystemConfigDeploymentTypeResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterSystemConfigDeploymentTypeResp: Codable {

    public var value: VcenterSystemConfigDeploymentTypeInfo

    public init(value: VcenterSystemConfigDeploymentTypeInfo) {
        self.value = value
    }


}

