//
// VcenterContentRegistriesHarborListResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterContentRegistriesHarborListResp: Codable {

    public var value: [VcenterContentRegistriesHarborSummary]

    public init(value: [VcenterContentRegistriesHarborSummary]) {
        self.value = value
    }


}

