//
// VcenterNamespaceManagementNetworksIPAssignmentMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Networks.IPAssignmentMode enumerated type defines various IP address assignment modes. */
public enum VcenterNamespaceManagementNetworksIPAssignmentMode: String, Codable {
    case dhcp = "DHCP"
    case staticrange = "STATICRANGE"

}
