//
// VcenterNamespacesNamespaceTemplatesInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespacesNamespaceTemplatesInfo: Codable {

    /** Identifier for the vSphere cluster associated with namespace template. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: ClusterComputeResource. When operations return a value of this structure as a result, the field will be an identifier for the resource type: ClusterComputeResource. */
    public var cluster: String
    /** Name of the namespace template. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: vcenter.namespaces.NamespaceTemplate. When operations return a value of this structure as a result, the field will be an identifier for the resource type: vcenter.namespaces.NamespaceTemplate. */
    public var template: String
    /** Resource quotas that this template defines. Quotas on the namespace resources. Refer to vcenter.namespace_management.NamespaceResourceOptions#get for the type of the value for this field. If unset, no resource constraints are defined in the namespace template. */
    public var resourceSpec: JSONValue?
    /** Storage that this template defines and will be associated with a namespace after namespace realization. */
    public var storageSpecs: [VcenterNamespacesInstancesStorageSpec]
    /** vSphere Networks that this template captures and are associated with the namespace after namespace realization. This field is unset if the cluster hosting this namespace uses NSXT_CONTAINER_PLUGIN as its network provider. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: vcenter.namespace_management.Network. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: vcenter.namespace_management.Network. */
    public var networks: [String]?
    /** Permissions associated with namespace template. If unset, only users with the Administrator role can use this template; for example, this template is applied to the namespace created by self-service-users with the Administrator role. */
    public var permissions: [VcenterNamespacesNamespaceTemplatesSubject]?
    /** Current set of virtual machine classes and Content Libraries associated with the template. This field is optional because it was added in a newer version than its parent node. */
    public var vmServiceSpec: VcenterNamespacesInstancesVMServiceSpec?

    public init(cluster: String, template: String, resourceSpec: JSONValue?, storageSpecs: [VcenterNamespacesInstancesStorageSpec], networks: [String]?, permissions: [VcenterNamespacesNamespaceTemplatesSubject]?, vmServiceSpec: VcenterNamespacesInstancesVMServiceSpec?) {
        self.cluster = cluster
        self.template = template
        self.resourceSpec = resourceSpec
        self.storageSpecs = storageSpecs
        self.networks = networks
        self.permissions = permissions
        self.vmServiceSpec = vmServiceSpec
    }

    public enum CodingKeys: String, CodingKey { 
        case cluster
        case template
        case resourceSpec = "resource_spec"
        case storageSpecs = "storage_specs"
        case networks
        case permissions
        case vmServiceSpec = "vm_service_spec"
    }


}

