//
// VcenterVmHardwareSerialUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmHardwareSerialUpdate: Codable {

    /** Specification for updating the virtual serial port. */
    public var spec: VcenterVmHardwareSerialUpdateSpec

    public init(spec: VcenterVmHardwareSerialUpdateSpec) {
        self.spec = spec
    }


}

