//
// VcenterCertificateManagementVcenterTlsResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterCertificateManagementVcenterTlsResp: Codable {

    public var value: VcenterCertificateManagementVcenterTlsInfo

    public init(value: VcenterCertificateManagementVcenterTlsInfo) {
        self.value = value
    }


}

