//
// VcenterDeploymentInstallInitialConfigRemotePscThumbprintRemoteSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterDeploymentInstallInitialConfigRemotePscThumbprintRemoteSpec: Codable {

    /** The IP address or DNS resolvable name of the remote PSC. */
    public var address: String
    /** The HTTPS port of the remote PSC. If unset, port 443 will be used. */
    public var httpsPort: Int64?

    public init(address: String, httpsPort: Int64?) {
        self.address = address
        self.httpsPort = httpsPort
    }

    public enum CodingKeys: String, CodingKey { 
        case address
        case httpsPort = "https_port"
    }


}

