//
// VcenterTokenserviceTokenExchangeExchange.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterTokenserviceTokenExchangeExchange: Codable {

    /** {@name ExchangeSpec} {@term structure} contains arguments that define exchange process. */
    public var spec: VcenterTokenserviceTokenExchangeExchangeSpec

    public init(spec: VcenterTokenserviceTokenExchangeExchangeSpec) {
        self.spec = spec
    }


}

