//
// VcenterNamespaceManagementClustersStats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementClustersStats: Codable {

    /** Overall CPU usage of the cluster, in MHz. This is the sum of CPU usage across all worker nodes in the cluster. */
    public var cpuUsed: Int64
    /** Total CPU capacity in the cluster available for vSphere Namespaces, in MHz. This is the sum of CPU capacities from all worker nodes in the cluster. */
    public var cpuCapacity: Int64
    /** Overall memory usage of the cluster, in mebibytes. This is the sum of memory usage across all worker nodes in the cluster. */
    public var memoryUsed: Int64
    /** Total memory capacity of the cluster available for vSphere Namespaces, in mebibytes. This is the sum of memory capacities from all worker nodesin the cluster. */
    public var memoryCapacity: Int64
    /** Overall storage used by the cluster, in mebibytes. This is the sum of storage used across all worker nodes in the cluster. */
    public var storageUsed: Int64
    /** Overall storage capacity of the cluster available for vSphere Namespaces, in mebibytes. This is the sum of total storage available from all worker nodes in the cluster. */
    public var storageCapacity: Int64

    public init(cpuUsed: Int64, cpuCapacity: Int64, memoryUsed: Int64, memoryCapacity: Int64, storageUsed: Int64, storageCapacity: Int64) {
        self.cpuUsed = cpuUsed
        self.cpuCapacity = cpuCapacity
        self.memoryUsed = memoryUsed
        self.memoryCapacity = memoryCapacity
        self.storageUsed = storageUsed
        self.storageCapacity = storageCapacity
    }

    public enum CodingKeys: String, CodingKey { 
        case cpuUsed = "cpu_used"
        case cpuCapacity = "cpu_capacity"
        case memoryUsed = "memory_used"
        case memoryCapacity = "memory_capacity"
        case storageUsed = "storage_used"
        case storageCapacity = "storage_capacity"
    }


}

