//
// VcenterVchaClusterConfigState.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Cluster.ConfigState enumerated type defines the VCHA configuration state. */
public enum VcenterVchaClusterConfigState: String, Codable {
    case configured = "CONFIGURED"
    case notconfigured = "NOTCONFIGURED"
    case invalid = "INVALID"
    case prepared = "PREPARED"

}
