//
// VcenterHvcLinksCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterHvcLinksCreate: Codable {

    /** Specification for the new link to be created. */
    public var spec: VcenterHvcLinksCreateSpec

    public init(spec: VcenterHvcLinksCreateSpec) {
        self.spec = spec
    }


}

