//
// VcenterTokenserviceInvalidScopeError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterTokenserviceInvalidScopeError: Codable {

    public var type: String?
    public var value: VcenterTokenserviceInvalidScope?

    public init(type: String?, value: VcenterTokenserviceInvalidScope?) {
        self.type = type
        self.value = value
    }


}

