//
// VcenterServicesServiceListDetailsRespValue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterServicesServiceListDetailsRespValue: Codable {

    public var key: String?
    public var value: VcenterServicesServiceInfo?

    public init(key: String?, value: VcenterServicesServiceInfo?) {
        self.key = key
        self.value = value
    }


}

