//
// VcenterIdentityProvidersListResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterIdentityProvidersListResp: Codable {

    public var value: [VcenterIdentityProvidersSummary]

    public init(value: [VcenterIdentityProvidersSummary]) {
        self.value = value
    }


}

