//
// VcenterResourcePoolSummary.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterResourcePoolSummary: Codable {

    /** Identifier of the resource pool. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: ResourcePool. When operations return a value of this structure as a result, the field will be an identifier for the resource type: ResourcePool. */
    public var resourcePool: String
    /** Name of the resource pool. */
    public var name: String

    public init(resourcePool: String, name: String) {
        self.resourcePool = resourcePool
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case resourcePool = "resource_pool"
        case name
    }


}

