//
// VcenterVmHardwareBootDeviceEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmHardwareBootDeviceEntry: Codable {

    /** Virtual device type. */
    public var type: VcenterVmHardwareBootDeviceType
    /** Virtual Ethernet device. Ethernet device to use as boot device for this entry. This field is optional and it is only relevant when the value of Device.Entry.type is ETHERNET. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: vcenter.vm.hardware.Ethernet. When operations return a value of this structure as a result, the field will be an identifier for the resource type: vcenter.vm.hardware.Ethernet. */
    public var nic: String?
    /** Virtual disk device. List of virtual disks in boot order. This field is optional and it is only relevant when the value of Device.Entry.type is DISK. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: vcenter.vm.hardware.Disk. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: vcenter.vm.hardware.Disk. */
    public var disks: [String]?

    public init(type: VcenterVmHardwareBootDeviceType, nic: String?, disks: [String]?) {
        self.type = type
        self.nic = nic
        self.disks = disks
    }


}

