//
// VcenterContentRegistriesRecurrence.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The {@name Recurrence} {@term enumerated type} defines the supported values for how often to run a specific operation for a container registry. */
public enum VcenterContentRegistriesRecurrence: String, Codable {
    case _none = "NONE"
    case daily = "DAILY"
    case weekly = "WEEKLY"

}
