//
// VcenterNamespaceManagementNetworksEdgesNSXAdvancedLBConfig.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementNetworksEdgesNSXAdvancedLBConfig: Codable {

    /** NSXAdvancedLBConfig.server is the address for the Avi Controller, used to configure Virtual Servers. */
    public var server: VcenterNamespaceManagementNetworksEdgesServer
    /** NSXAdvancedLBConfig.username is used by the AVI Kubernetes Operator to program the Avi Controller. */
    public var username: String
    /** NSXAdvancedLBConfig.password is the password for the username. */
    public var password: String
    /** NSXAdvancedLBConfig.certificate-authority-chain contains PEM-encoded CA chain which is used to verify x509 certificates received from the server. */
    public var certificateAuthorityChain: String

    public init(server: VcenterNamespaceManagementNetworksEdgesServer, username: String, password: String, certificateAuthorityChain: String) {
        self.server = server
        self.username = username
        self.password = password
        self.certificateAuthorityChain = certificateAuthorityChain
    }

    public enum CodingKeys: String, CodingKey { 
        case server
        case username
        case password
        case certificateAuthorityChain = "certificate_authority_chain"
    }


}

