//
// VcenterVmTemplateLibraryItemsHardwareCustomizationSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmTemplateLibraryItemsHardwareCustomizationSpec: Codable {

    /** Map of Ethernet network adapters to update. */
    public var nics: [VcenterVmTemplateLibraryItemsHardwareCustomizationSpecNics]?
    /** Idenfiers of disks to remove from the deployed virtual machine. */
    public var disksToRemove: [String]?
    /** Disk update specification for individual disks in the deployed virtual machine. */
    public var disksToUpdate: [VcenterVmTemplateLibraryItemsHardwareCustomizationSpecDisksToUpdate]?
    /** CPU update specification for the deployed virtual machine. */
    public var cpuUpdate: VcenterVmTemplateLibraryItemsCpuUpdateSpec?
    /** Memory update specification for the deployed virtual machine. */
    public var memoryUpdate: VcenterVmTemplateLibraryItemsMemoryUpdateSpec?

    public init(nics: [VcenterVmTemplateLibraryItemsHardwareCustomizationSpecNics]?, disksToRemove: [String]?, disksToUpdate: [VcenterVmTemplateLibraryItemsHardwareCustomizationSpecDisksToUpdate]?, cpuUpdate: VcenterVmTemplateLibraryItemsCpuUpdateSpec?, memoryUpdate: VcenterVmTemplateLibraryItemsMemoryUpdateSpec?) {
        self.nics = nics
        self.disksToRemove = disksToRemove
        self.disksToUpdate = disksToUpdate
        self.cpuUpdate = cpuUpdate
        self.memoryUpdate = memoryUpdate
    }

    public enum CodingKeys: String, CodingKey { 
        case nics
        case disksToRemove = "disks_to_remove"
        case disksToUpdate = "disks_to_update"
        case cpuUpdate = "cpu_update"
        case memoryUpdate = "memory_update"
    }


}

