//
// VcenterConfidentialComputingSgxHostsRegisterSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterConfidentialComputingSgxHostsRegisterSpec: Codable {

    /** The host&#39;s identifier. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: HostSystem. When operations return a value of this structure as a result, the field will be an identifier for the resource type: HostSystem. */
    public var hostId: String

    public init(hostId: String) {
        self.hostId = hostId
    }

    public enum CodingKeys: String, CodingKey { 
        case hostId = "host_id"
    }


}

