//
// VcenterVchaClusterModeInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVchaClusterModeInfo: Codable {

    /** Identifies the mode of the VCHA cluster. */
    public var mode: VcenterVchaClusterModeClusterMode

    public init(mode: VcenterVchaClusterModeClusterMode) {
        self.mode = mode
    }


}

