//
// VcenterNamespaceManagementSupervisorsNetworksWorkloadVSphereNetwork.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespaceManagementSupervisorsNetworksWorkloadVSphereNetwork: Codable {

    /**  VSphereNetwork.dvpg is the Managed Object ID of a vSphere Distributed Virtual Port Group. You can use it to connect to a vSphere Network.  When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: vSphereDistributedPortGroup. When operations return a value of this structure as a result, the field will be an identifier for the resource type: vSphereDistributedPortGroup. */
    public var dvpg: String

    public init(dvpg: String) {
        self.dvpg = dvpg
    }


}

