//
// VcenterNamespacesNamespaceTemplatesGetV2Resp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespacesNamespaceTemplatesGetV2Resp: Codable {

    public var value: VcenterNamespacesNamespaceTemplatesInfoV2

    public init(value: VcenterNamespacesNamespaceTemplatesInfoV2) {
        self.value = value
    }


}

