//
// VcenterNamespacesInstancesStats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespacesInstancesStats: Codable {

    /** Overall CPU usage of the namespace, in MHz. This is the sum of CPU usage across all pods in the Kubernetes namespace. */
    public var cpuUsed: Int64
    /** Overall memory usage of the namespace (in mebibytes). This is the sum of memory usage across all pods. */
    public var memoryUsed: Int64
    /** Overall storage used by the namespace (in mebibytes). This is the sum of storage used by pods across all datastores in the cluster associated with storage policies configured for the namespace. */
    public var storageUsed: Int64

    public init(cpuUsed: Int64, memoryUsed: Int64, storageUsed: Int64) {
        self.cpuUsed = cpuUsed
        self.memoryUsed = memoryUsed
        self.storageUsed = storageUsed
    }

    public enum CodingKeys: String, CodingKey { 
        case cpuUsed = "cpu_used"
        case memoryUsed = "memory_used"
        case storageUsed = "storage_used"
    }


}

