//
// VcenterVmHardwareAdapterScsiUpdateSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmHardwareAdapterScsiUpdateSpec: Codable {

    /** Bus sharing mode.   This field may only be modified if the virtual machine is not powered on.  If unset, the value is unchanged. */
    public var sharing: VcenterVmHardwareAdapterScsiSharing?

    public init(sharing: VcenterVmHardwareAdapterScsiSharing?) {
        self.sharing = sharing
    }


}

