//
// VcenterVmHardwareDiskUpdateSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmHardwareDiskUpdateSpec: Codable {

    /** Physical resource backing for the virtual disk.   This field may only be modified if the virtual machine is not powered on.  If unset, the value is unchanged. */
    public var backing: VcenterVmHardwareDiskBackingSpec?

    public init(backing: VcenterVmHardwareDiskBackingSpec?) {
        self.backing = backing
    }


}

