//
// VcenterNamespacesInstancesContentLibrarySpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterNamespacesInstancesContentLibrarySpec: Codable {

    /** Content library ID used by the Image Registry Service. The content library specified should exist in vSphere inventory. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: content.Library. When operations return a value of this structure as a result, the field will be an identifier for the resource type: content.Library. */
    public var contentLibrary: String
    /** Flag to indicate if the library is writable. When set to true new library items can be added to the content library in vSphere. A subscribed library is not allowed to be marked as writable. InvalidArgument error will be thrown if subscribed library is marked as writable at create/update/set. If unset, the library is read-only to Devops users. */
    public var writable: Bool?

    public init(contentLibrary: String, writable: Bool?) {
        self.contentLibrary = contentLibrary
        self.writable = writable
    }

    public enum CodingKeys: String, CodingKey { 
        case contentLibrary = "content_library"
        case writable
    }


}

