//
// VcenterDeploymentInstallPscReplicatedCheckResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterDeploymentInstallPscReplicatedCheckResp: Codable {

    public var value: VcenterDeploymentCheckInfo

    public init(value: VcenterDeploymentCheckInfo) {
        self.value = value
    }


}

