//
// VcenterVmGuestOperationsInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmGuestOperationsInfo: Codable {

    /** Guest operations availability. Whether or not the virtual machine is ready to process guest operations. */
    public var guestOperationsReady: Bool
    /** Interactive guest operations availability. Whether or not the virtual machine is ready to process interactive guest operations. */
    public var interactiveGuestOperationsReady: Bool

    public init(guestOperationsReady: Bool, interactiveGuestOperationsReady: Bool) {
        self.guestOperationsReady = guestOperationsReady
        self.interactiveGuestOperationsReady = interactiveGuestOperationsReady
    }

    public enum CodingKeys: String, CodingKey { 
        case guestOperationsReady = "guest_operations_ready"
        case interactiveGuestOperationsReady = "interactive_guest_operations_ready"
    }


}

