//
// VcenterStoragePoliciesVMListRespValue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterStoragePoliciesVMListRespValue: Codable {

    public var key: String?
    public var value: VcenterStoragePoliciesVMInfo?

    public init(key: String?, value: VcenterStoragePoliciesVMInfo?) {
        self.key = key
        self.value = value
    }


}

