//
// VcenterTrustedInfrastructureTrustAuthorityClustersKmsProvidersCurrentPeerCertificatesFilterSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterTrustedInfrastructureTrustAuthorityClustersKmsProvidersCurrentPeerCertificatesFilterSpec: Codable {

    /** Names that key server must have to match the filter (see CurrentPeerCertificates.Summary.server-name). If unset or empty, key servers with any name match the filter. */
    public var serverNames: [String]?
    /** Trust status that server certificates must have to match the filter (see CurrentPeerCertificates.Summary.trusted). If unset, trusted and untrusted server certificates match the filter. */
    public var trusted: Bool?

    public init(serverNames: [String]?, trusted: Bool?) {
        self.serverNames = serverNames
        self.trusted = trusted
    }

    public enum CodingKeys: String, CodingKey { 
        case serverNames = "server_names"
        case trusted
    }


}

