//
// VcenterTrustedInfrastructureTrustAuthorityClustersKmsProvidersCredentialSetTask.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** KMIP KMS password or AWS access key. */

public struct VcenterTrustedInfrastructureTrustAuthorityClustersKmsProvidersCredentialSetTask: Codable {




}

