//
// VcenterVmHardwareCdromDeviceAccessType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Cdrom.DeviceAccessType enumerated type defines the valid device access types for a physical device packing of a virtual CD-ROM device. */
public enum VcenterVmHardwareCdromDeviceAccessType: String, Codable {
    case emulation = "EMULATION"
    case passthru = "PASSTHRU"
    case passthruExclusive = "PASSTHRU_EXCLUSIVE"

}
