//
// VcenterVmGuestNetworkingInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmGuestNetworkingInfo: Codable {

    /** Client DNS values. Data assigned by DNS. If unset no DNS assigned value exists. */
    public var dnsValues: VcenterVmGuestDnsAssignedValues?
    /** Client DNS configuration. How DNS queries are resolved. If unset no DNS assigned value exists. */
    public var dns: VcenterVmGuestDnsConfigInfo?

    public init(dnsValues: VcenterVmGuestDnsAssignedValues?, dns: VcenterVmGuestDnsConfigInfo?) {
        self.dnsValues = dnsValues
        self.dns = dns
    }

    public enum CodingKeys: String, CodingKey { 
        case dnsValues = "dns_values"
        case dns
    }


}

