//
// VcenterVmHardwareCdromBackingInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmHardwareCdromBackingInfo: Codable {

    /** Backing type for the virtual CD-ROM device. */
    public var type: VcenterVmHardwareCdromBackingType
    /** Path of the image file backing the virtual CD-ROM device. This field is optional and it is only relevant when the value of Cdrom.BackingInfo.type is ISO_FILE. */
    public var isoFile: String?
    /** Name of the host device backing the virtual CD-ROM device.    This field will be unset if Cdrom.BackingInfo.auto-detect is true and the virtual CD-ROM device is not connected or no suitable device is available on the host. */
    public var hostDevice: String?
    /** Flag indicating whether the virtual CD-ROM device is configured to automatically detect a suitable host device. This field is optional and it is only relevant when the value of Cdrom.BackingInfo.type is HOST_DEVICE. */
    public var autoDetect: Bool?
    /** Access type for the device backing. This field is optional and it is only relevant when the value of Cdrom.BackingInfo.type is one of HOST_DEVICE or CLIENT_DEVICE. */
    public var deviceAccessType: VcenterVmHardwareCdromDeviceAccessType?

    public init(type: VcenterVmHardwareCdromBackingType, isoFile: String?, hostDevice: String?, autoDetect: Bool?, deviceAccessType: VcenterVmHardwareCdromDeviceAccessType?) {
        self.type = type
        self.isoFile = isoFile
        self.hostDevice = hostDevice
        self.autoDetect = autoDetect
        self.deviceAccessType = deviceAccessType
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case isoFile = "iso_file"
        case hostDevice = "host_device"
        case autoDetect = "auto_detect"
        case deviceAccessType = "device_access_type"
    }


}

