//
// VcenterVmStoragePolicyComplianceCheckSpec.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterVmStoragePolicyComplianceCheckSpec: Codable {

    /** Invoke compliance check on the virtual machine home directory if set to true. */
    public var vmHome: Bool
    /** Identifiers of the virtual machine&#39;s virtual disks for which compliance should be checked. If unset or empty, compliance check is invoked on all the associated disks. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: vcenter.vm.hardware.Disk. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: vcenter.vm.hardware.Disk. */
    public var disks: [String]?

    public init(vmHome: Bool, disks: [String]?) {
        self.vmHome = vmHome
        self.disks = disks
    }

    public enum CodingKeys: String, CodingKey { 
        case vmHome = "vm_home"
        case disks
    }


}

