//
// VcenterClusterListResp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VcenterClusterListResp: Codable {

    public var value: [VcenterClusterSummary]

    public init(value: [VcenterClusterSummary]) {
        self.value = value
    }


}

