//
// VcenterNamespaceManagementSupervisorServicesVersionsContentType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Versions.ContentType enumerated type defines the type of content that describes the format of Supervisor Service version definition. */
public enum VcenterNamespaceManagementSupervisorServicesVersionsContentType: String, Codable {
    case vsphereAppsYaml = "VSPHERE_APPS_YAML"
    case carvelAppsYaml = "CARVEL_APPS_YAML"
    case customYaml = "CUSTOM_YAML"

}
