//
// ContentregistrieshealthAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class ContentregistrieshealthAPI {
    /**
     Returns the health information of a container registry in the vCenter.
     
     - parameter registry: (path) Identifier of the registry. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func callGet(registry: String, completion: @escaping ((_ data: VcenterContentRegistriesHealthInfo?,_ error: Error?) -> Void)) {
        callGetWithRequestBuilder(registry: registry).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Returns the health information of a container registry in the vCenter.
     - GET /api/vcenter/content/registries/{registry}/health
     - API Key:
       - type: apiKey vmware-api-session-id 
       - name: session_id
     - examples: [{contentType=application/json, example={"empty": false}}]
     
     - parameter registry: (path) Identifier of the registry. 

     - returns: RequestBuilder<VcenterContentRegistriesHealthInfo> 
     */
    open class func callGetWithRequestBuilder(registry: String) -> RequestBuilder<VcenterContentRegistriesHealthInfo> {
        var path = "/api/vcenter/content/registries/{registry}/health"
        let registryPreEscape = "\(registry)"
        let registryPostEscape = registryPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{registry}", with: registryPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<VcenterContentRegistriesHealthInfo>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Returns the health information of a container registry in the vCenter.
     
     - parameter registry: (path) Identifier of the registry. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func callGet_0(registry: String, completion: @escaping ((_ data: VcenterContentRegistriesHealthResp?,_ error: Error?) -> Void)) {
        callGet_0WithRequestBuilder(registry: registry).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Returns the health information of a container registry in the vCenter.
     - GET /rest/vcenter/content/registries/{registry}/health
     - API Key:
       - type: apiKey vmware-api-session-id 
       - name: session_id
     - examples: [{contentType=application/json, example={"empty": false}}]
     
     - parameter registry: (path) Identifier of the registry. 

     - returns: RequestBuilder<VcenterContentRegistriesHealthResp> 
     */
    open class func callGet_0WithRequestBuilder(registry: String) -> RequestBuilder<VcenterContentRegistriesHealthResp> {
        var path = "/rest/vcenter/content/registries/{registry}/health"
        let registryPreEscape = "\(registry)"
        let registryPostEscape = registryPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{registry}", with: registryPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<VcenterContentRegistriesHealthResp>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
