//
// DeploymentinstallremotePscAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class DeploymentinstallremotePscAPI {
    /**
     Checks whether the remote PSC is reachable and the deployed vCenter Server can be registered with the remote PSC.
     
     - parameter requestBody: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func check(requestBody: VcenterDeploymentInstallRemotePscCheck? = nil, completion: @escaping ((_ data: VcenterDeploymentCheckInfo?,_ error: Error?) -> Void)) {
        checkWithRequestBuilder(requestBody: requestBody).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Checks whether the remote PSC is reachable and the deployed vCenter Server can be registered with the remote PSC.
     - POST /api/vcenter/deployment/install/remote-psc?action=check
     - API Key:
       - type: apiKey vmware-api-session-id 
       - name: session_id
     - examples: [{contentType=application/json, example={"empty": false}}]
     
     - parameter requestBody: (body)  (optional)

     - returns: RequestBuilder<VcenterDeploymentCheckInfo> 
     */
    open class func checkWithRequestBuilder(requestBody: VcenterDeploymentInstallRemotePscCheck? = nil) -> RequestBuilder<VcenterDeploymentCheckInfo> {
        let path = "/api/vcenter/deployment/install/remote-psc?action=check"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<VcenterDeploymentCheckInfo>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Checks whether the remote PSC is reachable and the deployed vCenter Server can be registered with the remote PSC.
     
     - parameter requestBody: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func check_0(requestBody: VcenterDeploymentInstallRemotePscCheck, completion: @escaping ((_ data: VcenterDeploymentInstallRemotePscCheckResp?,_ error: Error?) -> Void)) {
        check_0WithRequestBuilder(requestBody: requestBody).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Checks whether the remote PSC is reachable and the deployed vCenter Server can be registered with the remote PSC.
     - POST /rest/vcenter/deployment/install/remote-psc?action=check
     - API Key:
       - type: apiKey vmware-api-session-id 
       - name: session_id
     - examples: [{contentType=application/json, example={"empty": false}}]
     
     - parameter requestBody: (body)  

     - returns: RequestBuilder<VcenterDeploymentInstallRemotePscCheckResp> 
     */
    open class func check_0WithRequestBuilder(requestBody: VcenterDeploymentInstallRemotePscCheck) -> RequestBuilder<VcenterDeploymentInstallRemotePscCheckResp> {
        let path = "/rest/vcenter/deployment/install/remote-psc?action=check"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<VcenterDeploymentInstallRemotePscCheckResp>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
