//
// NamespaceManagementsupervisorstopologyAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class NamespaceManagementsupervisorstopologyAPI {
    /**
     Queries the current association between vSphere Zones and vSphere Clusters from the given Supervisor ID. A Supervisor can be running on one or multiple vSphere Zones, and each vSphere Zone is associated with one or more vSphere Clusters. Use the vSphere Cluster IDs obtained from Topology.get to call the APIs that requires a vSphere Cluster ID instead of a Supervisor.
     
     - parameter supervisor: (path) Identifier for a Supervisor. The parameter must be an identifier for the resource type: vcenter.namespace_management.supervisor.Supervisor. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func callGet(supervisor: String, completion: @escaping ((_ data: [VcenterNamespaceManagementSupervisorsTopologyInfo]?,_ error: Error?) -> Void)) {
        callGetWithRequestBuilder(supervisor: supervisor).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Queries the current association between vSphere Zones and vSphere Clusters from the given Supervisor ID. A Supervisor can be running on one or multiple vSphere Zones, and each vSphere Zone is associated with one or more vSphere Clusters. Use the vSphere Cluster IDs obtained from Topology.get to call the APIs that requires a vSphere Cluster ID instead of a Supervisor.
     - GET /api/vcenter/namespace-management/supervisors/{supervisor}/topology
     - API Key:
       - type: apiKey vmware-api-session-id 
       - name: session_id
     - examples: [{contentType=application/json, example={}}]
     
     - parameter supervisor: (path) Identifier for a Supervisor. The parameter must be an identifier for the resource type: vcenter.namespace_management.supervisor.Supervisor. 

     - returns: RequestBuilder<[VcenterNamespaceManagementSupervisorsTopologyInfo]> 
     */
    open class func callGetWithRequestBuilder(supervisor: String) -> RequestBuilder<[VcenterNamespaceManagementSupervisorsTopologyInfo]> {
        var path = "/api/vcenter/namespace-management/supervisors/{supervisor}/topology"
        let supervisorPreEscape = "\(supervisor)"
        let supervisorPostEscape = supervisorPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{supervisor}", with: supervisorPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[VcenterNamespaceManagementSupervisorsTopologyInfo]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
