//
// SystemConfigdeploymentTypeAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SystemConfigdeploymentTypeAPI {
    /**
     Get the type of the vCenter appliance.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func callGet(completion: @escaping ((_ data: VcenterSystemConfigDeploymentTypeInfo?,_ error: Error?) -> Void)) {
        callGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get the type of the vCenter appliance.
     - GET /api/vcenter/system-config/deployment-type
     - API Key:
       - type: apiKey vmware-api-session-id 
       - name: session_id
     - examples: [{contentType=application/json, example={"empty": false}}]

     - returns: RequestBuilder<VcenterSystemConfigDeploymentTypeInfo> 
     */
    open class func callGetWithRequestBuilder() -> RequestBuilder<VcenterSystemConfigDeploymentTypeInfo> {
        let path = "/api/vcenter/system-config/deployment-type"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<VcenterSystemConfigDeploymentTypeInfo>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get the type of the vCenter appliance.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func callGet_0(completion: @escaping ((_ data: VcenterSystemConfigDeploymentTypeResp?,_ error: Error?) -> Void)) {
        callGet_0WithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get the type of the vCenter appliance.
     - GET /rest/vcenter/system-config/deployment-type
     - API Key:
       - type: apiKey vmware-api-session-id 
       - name: session_id
     - examples: [{contentType=application/json, example={"empty": false}}]

     - returns: RequestBuilder<VcenterSystemConfigDeploymentTypeResp> 
     */
    open class func callGet_0WithRequestBuilder() -> RequestBuilder<VcenterSystemConfigDeploymentTypeResp> {
        let path = "/rest/vcenter/system-config/deployment-type"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<VcenterSystemConfigDeploymentTypeResp>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Reconfigure the type of the vCenter appliance.
     
     - parameter requestBody: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func reconfigure(requestBody: VcenterSystemConfigDeploymentTypeReconfigure? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        reconfigureWithRequestBuilder(requestBody: requestBody).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Reconfigure the type of the vCenter appliance.
     - PUT /api/vcenter/system-config/deployment-type
     - API Key:
       - type: apiKey vmware-api-session-id 
       - name: session_id
     
     - parameter requestBody: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func reconfigureWithRequestBuilder(requestBody: VcenterSystemConfigDeploymentTypeReconfigure? = nil) -> RequestBuilder<Void> {
        let path = "/api/vcenter/system-config/deployment-type"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Reconfigure the type of the vCenter appliance.
     
     - parameter requestBody: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func reconfigure_0(requestBody: VcenterSystemConfigDeploymentTypeReconfigure, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        reconfigure_0WithRequestBuilder(requestBody: requestBody).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Reconfigure the type of the vCenter appliance.
     - POST /rest/vcenter/system-config/deployment-type
     - API Key:
       - type: apiKey vmware-api-session-id 
       - name: session_id
     
     - parameter requestBody: (body)  

     - returns: RequestBuilder<Void> 
     */
    open class func reconfigure_0WithRequestBuilder(requestBody: VcenterSystemConfigDeploymentTypeReconfigure) -> RequestBuilder<Void> {
        let path = "/rest/vcenter/system-config/deployment-type"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: requestBody)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
