//
// VchaclusterdeploymentTypeAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class VchaclusterdeploymentTypeAPI {
    /**
     Retrieves the deployment type of a VCHA cluster.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func callGet(completion: @escaping ((_ data: VcenterVchaClusterDeploymentTypeInfo?,_ error: Error?) -> Void)) {
        callGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Retrieves the deployment type of a VCHA cluster.
     - GET /api/vcenter/vcha/cluster/deployment-type
     - API Key:
       - type: apiKey vmware-api-session-id 
       - name: session_id
     - examples: [{contentType=application/json, example={"empty": false}}]

     - returns: RequestBuilder<VcenterVchaClusterDeploymentTypeInfo> 
     */
    open class func callGetWithRequestBuilder() -> RequestBuilder<VcenterVchaClusterDeploymentTypeInfo> {
        let path = "/api/vcenter/vcha/cluster/deployment-type"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<VcenterVchaClusterDeploymentTypeInfo>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Retrieves the deployment type of a VCHA cluster.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func callGet_0(completion: @escaping ((_ data: VcenterVchaClusterDeploymentTypeResp?,_ error: Error?) -> Void)) {
        callGet_0WithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Retrieves the deployment type of a VCHA cluster.
     - GET /rest/vcenter/vcha/cluster/deployment-type
     - API Key:
       - type: apiKey vmware-api-session-id 
       - name: session_id
     - examples: [{contentType=application/json, example={"empty": false}}]

     - returns: RequestBuilder<VcenterVchaClusterDeploymentTypeResp> 
     */
    open class func callGet_0WithRequestBuilder() -> RequestBuilder<VcenterVchaClusterDeploymentTypeResp> {
        let path = "/rest/vcenter/vcha/cluster/deployment-type"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<VcenterVchaClusterDeploymentTypeResp>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
